### ISSUE TITLE
Create a Answer DB model

### ISSUE THREAD

**Issue by starmarek** [KerLau/Quiz-app#40]
fields:
 - foreign key to user (one user can have many answers, but one answer can only have ony user) one2many relation
 - foreign key to category (one category can have many answers, but one answer can only have one category) one2many relation

**Comment by Kenny4297** [comment]
Hi @KerLau, I have the solution! May I make a PR?

**Comment by KerLau** [comment]
> Hi @KerLau, I have the solution! May I make a PR?

Hi @Kenny4297 . This is our Web Development final project for the courses. Would be happy to see your approach for it of course
