### ISSUE TITLE
Fe component to show the leaderboard

### ISSUE THREAD

**Issue by starmarek** [KerLau/Quiz-app#44]
- Navigation to the leaderboards, should be avialalbe in the top panel, after the user has logged in
- When rendering the component/page, fetch the data from BE
- Create some kind of a switch/dropdown to switch between the leaderboards (to render different leadebordes for each category)

**Comment by Kenny4297** [comment]
Hi [@starmarek](#), love to help here. I'm curious about how you plan to store the leaderboards. If it's on the back-end, here are some options:

1) Add a 'score' field to each user's model.
2) Create a new model called 'Leaderboard'.

Alternatively, we could use a simple JSON file to store scores. While not a back-end solution, it's still feasible.

Personally, I'd recommend storing each user's score in local storage for simplicity, as the scores don't contain sensitive data, thus eliminating the need for API requests.

Let me know your preference and I can get started right away!

**Comment by starmarek** [comment]
Thanks for your input @Kenny4297. I am not being actively involved in the project. Any suggestions or inquiries should be directed to @KerLau.
